apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-provisioning
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd-system
spec:
  destination:
    namespace: keda-system
  project: default
  source:
    repoURL: https://github.com/seemscloud/argocd-kustomize-keda.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true