apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-deployment
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd-system
spec:
  destination:
    namespace: keda-system
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.8.2
    helm:
      parameters:
        - name: prometheus.metricServer.enabled
          value: "true"
        - name: prometheus.operator.enabled
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true